#!/bin/sh

SVN=/usr/bin/svn
DIR=$1
shift

test "$1" = "commit" -a -d $DIR/.svn || exit 1

diffstr=$($SVN diff $DIR | perl -n -E '$file = $1 if /^\Q+++\E\s+([^\s]+)/; if (/#.*?\btest\b/) { say($file), $file = "" if $file; say }')

[ x"$diffstr" = "x" ] || {
    /bin/echo -e "\e[38;5;9m===>\e[0m"
    /bin/echo -e "$diffstr"
    /bin/echo -e "\e[38;5;9mtest sections found\e[0m"
    exit 1
}

exit 0
 
    



